name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        poetry-version: ["1.7.1"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python Versions
      uses: actions/setup-python@v4
      with:
        python-version: |
          3.8
          3.9
          3.10
          3.11
          3.12
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v3.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - name: Install Dependencies
      run: |
        poetry install --only test
    - name: Test with Tox and PyTest
      run: |
        poetry run tox
